#!/bin/bash
# Clean up files and directories by leveraging the .gitignore file generated by Android Studio.
# Use: dirCleaner_Android.sh <Android directory>
# 2023-09-16 : Debian 12

arg="$1"
today=$(date +%Y-%m-%d)
output="/tmp/log-directoryCleanerAndroid-$today"
temp="/tmp/directoryCleanerAndroid.txt"

echo "Start ..."
if [[ "$arg" == "" ]]; then arg=".";fi
if [[ ! -d "$arg" ]]; then 
    echo "$arg: Not found!"
    echo "Check the directory to be cleaned and try again!"
    exit 0
fi
echo "Search: \"$arg\""

list=(\
*.iml \
.DS_Store \
.cxx
.externalNativeBuild \
.gradle \
.idea \
build \
captures \
gradle \
local.properties)
list+=(libs .gitignore .git)  # optional

echo "Result: $output" > $output
ls -Ra "$arg" | grep .*:$ > $temp
while read line; do
    dir=$(echo $line | sed -r "s/\://g")
    if [[ ! -d "$dir" ]]; then continue; fi
    echo "Check: \"$dir\""
    for item in "${list[@]}"; do
        remove=0
        search="$dir/$item"
        if [[ -d  "$search" ]]; then remove=1; fi
        if [[ -f  "$search" ]]; then remove=1; fi
        if [[ $remove -eq 1 ]]; then
            echo "Removed: $search" >> $output
            rm -rf "$search"
        fi
    done
done < $temp

echo "Finished!"
cat $output

exit 0